branches:
  only:
  - master
language: scala
scala:
- 2.10.4
- 2.11.7
jdk:
- openjdk7
- oraclejdk8
services:
- cassandra
cache:
  directories:
  - "~/.ivy2"
  apt: true
sbt_args: "-Dsbt.log.noformat=true -sbt-dir ~/.sbt"
after_success:
- sh "$TRAVIS_BUILD_DIR/.travis.release.sh"
env:
  global:
  - secure: PTF8hqNHI4ci6GN/umaXufJujuVxRjZdWg/s31Dj6oWlYuSzrC1Tfp9+cabwNLu6Hu/FXKLlIFm95Px3Fv/VfaA3a1r7zD0JXOMo7Ukw8SoZIiHwRkJuI/Ex+UKCIh69oeBeUDhyTYzwgQmFN9ProdbZW8jcOSSJ6zpprmhnOcKTWzt7ZWtBRev21pZWWwrH5XJNn6njIwY9slGQkePJ95RcmIvXe1//pWmcFdhKRqMrH1lTuCyKnCJt/+GVoKqIpdQ4rW5TDif3F4HAow37cSoZFSaSartHMIKP7WgbOFlpByCo8nRAiLZInrefYvBCgF+1sc7CADqpybJFr1LWb7QOi+g1F6vHjpCxVHnUk5dlYyCx+VRGqcBtKWCuNwma4I6eu7/SkM46ec0yQzb6BWx8EgUamUp6XjrXFiH5Vnc2U2P2uMjvqL9OKXEZx5kZGgqfLSvtJdM6tdKdGOBr26U+7H7KF1YO3bA6LHJn/stQhgDyE9zX56m3n1Addt/bQpt0EjjUPe1VQfDptt0KXnGw04YFRfQMzStPU9iMZMmpIBHFr0XXqQ3IBu2pgBLhkRcqLUE1+KlRjnKq/UAa4cMAnx5DfLCRj2TlmsScbK4OLY0cZoy1JjOFpWLFJ7RorDYz894nAor+DDLyFus6t+GLYwtCe/hxNam5pMWKzko=
  - secure: DiHT2XAk9rJ3RjxKx4kNLUob/tdTtKi60JHrOxCUk5cTzAp+6DB8rWbUt9kMCYVyg+3jbDKj0tRx40PYckbx8e6qdv5QHJuFaVdL7TYfCJNPq+NV3KNOYRhm28fZVQnqhV51QG3AzZVnDE1Hi7k+TW3h/sojmbJzqSYuHuduTELeeIeQSg5tPBt9M5kDBLBiRmbQza7Cq9g/0mhqEa2HtzkHTIKP5Z12zCy+VIF22Iw08qCSKxKxOiM/UNOQUt7QfC6dd9Vi0Q1WlstJlLNVEGGY+30WVlCxCBa04UvTVgBqdDRfNGXYTc6lDVEmzyWVdNBK9VadB6jjsfe6beAFRtA7kptwmKtNZfyBF+rrDbEkv8jg8aMeXNW/4oI2Kg6vSjdwP+ra6WS+f8xlJquVqTdOrE+pFEczptabHBKFD/ZWOfQPesbLG2oBqYl2vMetX632GboNdL9HMQuZNT5X6ouvoKKwyjfSMyA7igSUdELgFm/4k4my5b35WLNzNpkSK3IbQieVpE2Hl7c2Ioq9PkaLQgsPLZIrWO2QDrAK0axHpKASoGRYEPqXONhruExKs6A+rtOir7IUEisCQQVd5hm0OqjCUxTpAguZXZHFTKNYJy+iMrN+IwkE7zApw6bbjj0DbAZs5/Q/2s2XCQeyYO8INPxJ3/+b+RAyO2Dj8Ao=
  - secure: T3735abXubIOPDYQ+NJweEGDl/laurlqfUYsMRi71fwXR5LiOQqp1ImAc/bzEThq6yxscnOJjP6jHkVB2Zav6Wh1mfjyfFQROHTfHzW5eP6drO12emXkeqfhb+RSz1pBfG0L9ctRBtYB0yYwXa48qBFSvDmsqRNHhz+IZ6oM/MSaMmFSTPncICo/Gj3//4wEhFXgREYnCRxS/9dTK0pNnPo30Nj4g0OcLfcheRzwTfxGmmXd2/r+/Z/S+chQq5hoKPzQ/fSsdjVT4BVsMc0MgzcqNfgMsh0WJpfXeqe6KiEYWkjGDhORoiT9ygLOEZBrkmaE6H7DHVQ0MVhefY85iDogwW66aM1G/oESLv5l1juBo89qHmISjM+gLdCvMLIECCPCRsGsOVOc6LX5tOVbdUM87xO4WrFXy37Z1fLEO78ReNZ5Ksc2R3pWVL9wgG9GseLDzJBMadYLvvXtiZTfK9/+/NmygC2zDHwFeAIKK70cgE7Z4hMpj7PpSRDOZwRAXdCBVXUDKpTIAL8Z4bQmBYN6DTP1aYv4CFyLweVcK9jTucBVVx3rre5NS7YYIpBi0DAIgHvH1mvSbjGeppVjaE/1ynox72qZOGuEOD2E93NiYqkT+3e/RC4m0IG/QjvLkON4eoVo5iEiDC3vhwuBxjo2QKGCrhR0xDPdX09HhHs=
  - secure: Bh3YocPMOL8hGrVkiV/JcDqOghXdKY9mI8vzUeOmanrmHYnZSc/eSJnUpVdxMykuKNvnmeo3Yn2rNGFYboJVMyf/l7/vM2UnCzCiykODErpwJUNju8PjaMeAZm9Hwv9EYdwycMYLpRyl4tR4wGlrBYDvDYtG4i3wFXgBQoD7nfBVXFas6o/nncJjbA80keOg3wZQkvkOKTKf8E/+aCdXfpTWeAj9qmPYIyp934/vuMw3s+7+mG3wnDJrPd5qRTo6NO00J88rPGoaAms1DKHa0oEUv5FYkhFITJ2BognPa8/q68EBv5DGeJHXA9HP/rUdtZl9NN1ZqCAMnIuNXcAK+hVmt/GDSfh07V8hEKmjQLuwsUG5R9ARRwv3ilVvUZgNz4JUnamsXkH+t3sEfVBMdUMqgOKpqp1Uj+d7+xI5XErOPx8lcgMn1NCm4nI2DbTfPTjQephoF1UMicFNA5sH7+hhqI7rOmiAsAc8LALbrXFZjv2MP2HBPyXsPR5FdMWosZ/VEuNiAkYnLHF1ucn8R7yZIlvFctGD4641W+B+fTgty8cbIlhCw5DB0L6WqZwwW6g281+PAi7pEl0xBAe5t4paOgYK74EoI8wkDE7YlvEOrzhfGip7nRr5NQ6tRjaxQWzU4CcocHD7EWVDtE3R9Bu3D4Qxqmki9ZFmZzrRCmM=
